Bazel 0.25.2, shellcheck fixups

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -40,46 +40,45 @@ BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
 
-# default to Bazel version 0.3.0
+# default to Bazel version 0.25.2
 if [[ ! -v BAZEL_VERSION ]]; then
-  BAZEL_VERSION="0.3.0"
+  BAZEL_VERSION="0.25.2"
 fi
 
 # install Java 1.8
 JVM_BUILDPACK="https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/jvm-common.tgz"
-JVM_COMMON_BUILDPACK=${JVM_COMMON_BUILDPACK:-${JVM_BUILDPACK}}
-echo "-----> Install Java 8 from ${JVM_COMMON_BUILDPACK}"
+JVM_COMMON_BUILDPACK=${JVM_COMMON_BUILDPACK:-$JVM_BUILDPACK}
+echo "-----> Install Java 8 from $JVM_COMMON_BUILDPACK"
 mkdir -p /tmp/jvm-common
-curl --retry 3 --silent --location $JVM_COMMON_BUILDPACK \
+curl --retry 3 --silent --location "$JVM_COMMON_BUILDPACK" \
   | tar xzm -C /tmp/jvm-common --strip-components=1
 . /tmp/jvm-common/bin/util
 . /tmp/jvm-common/bin/java
 
 # Set this environment variable for Bazel, so it can use JDK 1.8.
-export JAVA_HOME="${BUILD_DIR}/.jdk"
-install_java_with_overlay ${BUILD_DIR} | indent
+export JAVA_HOME="$BUILD_DIR/.jdk"
+install_java_with_overlay "$BUILD_DIR" | indent
 echo "-----> Java 8 installed"
 
 # Create the CACHE_DIR if it doesn't exist.
 if [[ ! -d ${CACHE_DIR} ]]; then
-  mkdir ${CACHE_DIR}
+  mkdir "$CACHE_DIR"
 fi
 
 # Fetch the Bazel installer
 # TODO: consider keeping the Bazel and Java installs in cache.
-URL="https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/"
-URL+="bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
+URL="https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/"
+URL+="bazel-$BAZEL_VERSION-installer-linux-x86_64.sh"
 echo "-----> Downloading Bazel from $URL"
-export BAZEL_INSTALLER=${CACHE_DIR}/install.sh
-curl -L -o "${BAZEL_INSTALLER}" "${URL}"
-if [[ $? -ne 0 ]]; then
-  echo "download failed" >&2
+export BAZEL_INSTALLER="$CACHE_DIR/install.sh"
+if ! curl -L -o "$BAZEL_INSTALLER" "$URL"; then
+  echo "Download failed" >&2
   exit 1
 fi
 
 BASE="${BUILD_DIR}/bazel"
 
-if ! grep -q -e "${BASE}" "${PATH}"; then
+if ! grep -q -e "$BASE" "$PATH"; then
   # update path if necessary
   PATH=${BASE}:$PATH
   export PATH
@@ -87,33 +86,33 @@ fi
 
 # Install Bazel inside ${BASE}
 echo "-----> Installing Bazel"
-bash "${BAZEL_INSTALLER}" \
-  --base="${BASE}" \
-  --bazelrc="${HOME}/bazel.bazelrc" \
-  --bin="${BASE}/binary" | indent
+bash "$BAZEL_INSTALLER" \
+  --base="$BASE" \
+  --bazelrc="$HOME/bazel.bazelrc" \
+  --bin="$BASE/binary" | indent
 echo "-----> Bazel installed"
 
 # Custom bazelrc file for Docker
 echo "-----> configure Bazel"
-echo -e "\nstartup --batch" >> $BUILD_DIR/bazel.bazelrc
+echo -e "\nstartup --batch" >> "$BUILD_DIR"/bazel.bazelrc
 echo -e "\nbuild --spawn_strategy=standalone --genrule_strategy=standalone" \
-  >> $BUILD_DIR/bazel.bazelrc
+  >> "$BUILD_DIR/bazel.bazelrc"
 
 # Build app
 echo "-----> Building app"
-BAZEL="${BASE}/bin/bazel --bazelrc=${BUILD_DIR}/bazel.bazelrc"
-cd $BUILD_DIR
+BAZEL="${BASE}/bin/bazel --bazelrc=$BUILD_DIR/bazel.bazelrc"
+cd "$BUILD_DIR"
 ${BAZEL} clean
-${BAZEL} build -c opt $(cat build_path)
+${BAZEL} build -c opt "$(cat build_path)"
 
 # Find absolute path to deploy jar. For whatever reason. Heroku doesn't like the
 # Bazel symlinks.
-BAZEL_BIN=$(ls -l | grep "bazel-bin" | sed "s/.* -> //")
+BAZEL_BIN="$(ls -l | grep "bazel-bin" | sed "s/.* -> //")"
 
 # Copy the deploy jar to the build directory
-cp ${BAZEL_BIN}/$(cat build_path | sed "s/:/\//") $BUILD_DIR/app.jar
+cp "$BAZEL_BIN"/"$(sed "s/:/\//" build_path)" "$BUILD_DIR/app.jar"
 
 # Clean up other artifacts so that the slug is smaller
 echo "-----> Cleaning up build directory"
 ${BAZEL} clean
-rm -rf ${BUILD_DIR}/bazel
+rm -rf "$BUILD_DIR/bazel"
